### ISSUE TITLE
MOTIS: Figure out why we can't add more feeds

### ISSUE THREAD

**Issue by jbruechert** [public-transport/transitous#81]
Current working theory: We might have overflown the type used for indexing stops

**Comment by felixguendling** [comment]
Stops are currently limited to 2^22 = 4194304 due to [footpaths.h](https://github.com/motis-project/nigiri/blob/1125c21a93c7ccdd08aa8be07bb43b5a73fcc176/include/nigiri/footpath.h#L17). More stations = less maximum foopath length. However, it probably makes sense to not support extremely long footpaths anyway.
